apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8app
  template:
    metadata:
      labels:
        app: k8app
    spec:
      containers:
      - name: k8app
        image: k8demos.azurecr.io/k8app:1
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 1G # 0.1G For Start
          limits:
            cpu: 500m
            memory: 1G # 0.1G For Start
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule